include:
  - project: "mrpelz/boilerplate"
    ref: main
    file: "/gitlab/.docker.gitlab-ci.yml"

make images:
  rules:
    - when: never

make images (amd64):
  extends: make images
  parallel:
    matrix:
      - ARCH: amd64
        TAG: x86_64
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
      variables:
        VERSION_TAG: "latest"
    - if: $CI_COMMIT_TAG
      variables:
        VERSION_TAG: "pre-${CI_COMMIT_TAG_MESSAGE}"

make images (arm64):
  extends: make images
  allow_failure: true
  parallel:
    matrix:
      - ARCH: arm64
        TAG: arm64
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
  variables:
    VERSION_TAG: "latest"

make multi-arch images:
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
  variables:
    VERSION_TAG: "latest"
