apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: {}
  labels: {}
  name: example  # irgendein name
  namespace: iot-test
spec:
  ingressClassName: nginx
  rules:
    - host: iot-test.rancher.lan.wurstsalat.cloud  # irgendwas. hauptsache der DNS zeigt auf rancher
      http:
        paths:
          - backend:
              service:
                name: example  # siehe service.yaml
                port:
                  number: 80
            path: /
            pathType: Prefix
