apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.org/websocket-services: "iot-monolith-http"
  labels: {}
  name: iot-monolith
spec:
  ingressClassName: nginx
  rules:
    - host: "{SUB_DOMAIN}.{DOMAIN}"
      http:
        paths:
          - backend:
              service:
                name: iot-monolith-http
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - "{SUB_DOMAIN}.{DOMAIN}"
