apiVersion: v1
kind: PersistentVolume
metadata:
  name: iot-monolith
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  local:
    path: /var/opt/iot-monolith/{DIRECTORY}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - rancher-1
                - rancher-2
                - rancher-3
                - rancher-iot
