apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iot-monolith
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: iot-monolith
