include:
  - project: "mrpelz/boilerplate"
    ref: main
    file: "/gitlab/.container.gitlab-ci.yml"

make images:
  rules:
    - when: never

make images (amd64):
  extends: make images
  parallel: 1
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
      variables:
        VERSION_TAG: "latest"
    - if: $CI_COMMIT_TAG
      variables:
        VERSION_TAG: "pre-${CI_COMMIT_TAG_MESSAGE}"
  variables:
    ARCH: amd64
    TAG: x86_64

make images (arm64):
  extends: make images
  parallel: 1
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
  variables:
    ARCH: arm64
    TAG: arm64
    VERSION_TAG: "latest"

make multi-arch images:
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
      variables:
        VERSION_TAG: "latest"
        PLATFORMS: "linux/amd64,linux/arm64"
    - if: $CI_COMMIT_TAG
      variables:
        VERSION_TAG: "pre-${CI_COMMIT_TAG_MESSAGE}"
        PLATFORMS: "linux/amd64"
