import { properties as bedroomProperties } from './rooms/bedroom.js';
import { properties as diningRoomProperties } from './rooms/dining-room.js';
import { properties as hallwayProperties } from './rooms/hallway.js';
import { properties as kitchenProperties } from './rooms/kitchen.js';
import { properties as livingRoomProperties } from './rooms/living-room.js';
import { properties as mrpelzBathroomProperties } from './rooms/mrpelz-bathroom.js';
import { properties as officeProperties } from './rooms/office.js';
import { outputGrouping } from '../lib/tree/properties/actuators.js';
import { properties as storageRoomProperties } from './rooms/storage-room.js';
import { properties as tsiaBathroomProperties } from './rooms/tsia-bathroom.js';

export const all = outputGrouping(
  [
    bedroomProperties.bedLedDownlightRed,
    bedroomProperties.bedLedRGB.b,
    bedroomProperties.bedLedRGB.g,
    bedroomProperties.bedLedRGB.r,
    bedroomProperties.bedLedW,
    bedroomProperties.ceilingLight,
    bedroomProperties.nightstandLedLeft,
    bedroomProperties.nightstandLedRight,
    bedroomProperties.stoneLamp,
    diningRoomProperties.ceilingLight,
    diningRoomProperties.fan,
    diningRoomProperties.kallaxLedRGB.b,
    diningRoomProperties.kallaxLedRGB.g,
    diningRoomProperties.kallaxLedRGB.r,
    diningRoomProperties.kallaxLedSide,
    diningRoomProperties.kallaxLedW,
    diningRoomProperties.standingLamp,
    diningRoomProperties.tableLight,
    hallwayProperties.ceilingLightBack,
    hallwayProperties.ceilingLightFront,
    kitchenProperties.ledLeftCWhite,
    kitchenProperties.ledLeftFloodlight,
    kitchenProperties.ledLeftWWhite,
    kitchenProperties.ledRightCWhite,
    kitchenProperties.ledRightFloodlight,
    kitchenProperties.ledRightWWhite,
    livingRoomProperties.ceilingLight,
    livingRoomProperties.fan,
    livingRoomProperties.standingLamp,
    mrpelzBathroomProperties.ceilingLight,
    mrpelzBathroomProperties.mirrorHeating,
    mrpelzBathroomProperties.mirrorLed,
    mrpelzBathroomProperties.mirrorLight,
    mrpelzBathroomProperties.nightLight,
    officeProperties.ceilingLight,
    officeProperties.floodLight,
    officeProperties.workbenchLedCWhite,
    officeProperties.workbenchLedWWhite,
    storageRoomProperties.ceilingLight,
    tsiaBathroomProperties.ceilingLight,
    tsiaBathroomProperties.mirrorLed,
    tsiaBathroomProperties.mirrorLight,
    tsiaBathroomProperties.nightLight,
  ],
  'group'
);

export const allLights = outputGrouping([
  bedroomProperties.bedLedDownlightRed,
  bedroomProperties.bedLedRGB.b,
  bedroomProperties.bedLedRGB.g,
  bedroomProperties.bedLedRGB.r,
  bedroomProperties.bedLedW,
  bedroomProperties.ceilingLight,
  bedroomProperties.nightstandLedLeft,
  bedroomProperties.nightstandLedRight,
  bedroomProperties.stoneLamp,
  diningRoomProperties.ceilingLight,
  diningRoomProperties.kallaxLedRGB.b,
  diningRoomProperties.kallaxLedRGB.g,
  diningRoomProperties.kallaxLedRGB.r,
  diningRoomProperties.kallaxLedSide,
  diningRoomProperties.kallaxLedW,
  diningRoomProperties.standingLamp,
  diningRoomProperties.tableLight,
  hallwayProperties.ceilingLightBack,
  hallwayProperties.ceilingLightFront,
  kitchenProperties.ledLeftCWhite,
  kitchenProperties.ledLeftFloodlight,
  kitchenProperties.ledLeftWWhite,
  kitchenProperties.ledRightCWhite,
  kitchenProperties.ledRightFloodlight,
  kitchenProperties.ledRightWWhite,
  livingRoomProperties.ceilingLight,
  livingRoomProperties.standingLamp,
  mrpelzBathroomProperties.ceilingLight,
  mrpelzBathroomProperties.mirrorLed,
  mrpelzBathroomProperties.mirrorLight,
  mrpelzBathroomProperties.nightLight,
  officeProperties.ceilingLight,
  officeProperties.floodLight,
  officeProperties.workbenchLedCWhite,
  officeProperties.workbenchLedWWhite,
  storageRoomProperties.ceilingLight,
  tsiaBathroomProperties.ceilingLight,
  tsiaBathroomProperties.mirrorLed,
  tsiaBathroomProperties.mirrorLight,
  tsiaBathroomProperties.nightLight,
]);

export const kitchenAdjacentLights = outputGrouping([
  diningRoomProperties.ceilingLight,
  diningRoomProperties.kallaxLedRGB.b,
  diningRoomProperties.kallaxLedRGB.g,
  diningRoomProperties.kallaxLedRGB.r,
  diningRoomProperties.kallaxLedSide,
  diningRoomProperties.kallaxLedW,
  diningRoomProperties.standingLamp,
  diningRoomProperties.tableLight,
  hallwayProperties.ceilingLightBack,
  hallwayProperties.ceilingLightFront,
  kitchenProperties.ledLeftCWhite,
  kitchenProperties.ledLeftFloodlight,
  kitchenProperties.ledLeftWWhite,
  kitchenProperties.ledRightCWhite,
  kitchenProperties.ledRightFloodlight,
  kitchenProperties.ledRightWWhite,
  livingRoomProperties.ceilingLight,
  livingRoomProperties.standingLamp,
]);
