export default {
  trendFactorThreshold: 0.005,
  unitMap: {
    brightness: 'lux',
    co: 'ppm',
    co2: 'ppm',
    eco2: 'ppm',
    humidity: 'percent-rh',
    pm025: 'micrograms/m3',
    pm10: 'micrograms/m3',
    precipitation: 'mm/h',
    pressure: 'hpa',
    temperature: 'deg-c',
    tvoc: 'ppb',
  },
  valueSanity: {
    brightness: {
      round: 2,
    },
    default: {
      round: 1,
    },
    eco2: {
      round: 0,
    },
    pressure: {
      divide: 100,
      round: 0,
    },
    tvoc: {
      round: 0,
    },
  },
  webApi: {
    extensions: {
      map: {
        section: 'map',
      },
    },
    sort: {
      categories: [
        '_top',
        'connections',
        'ahu-in',
        'ahu-out',
        'air',
        'lamps',
        'doors',
        'other',
        '_bottom',
      ],
      groups: [
        '_top',
        'temperature',
        'humidity',
        'brightness',
        'pressure',
        'pm10',
        'pm025',
        'co',
        'co2',
        'eco2',
        'tvoc',
        'precipitation',
        'door',
        'group',
        'front',
        'back',
        'ceiling-lamp',
        'standing-lamp',
        'stone-lamp',
        'flood-lamp',
        'lamp',
        'led',
        'left',
        'right',
        'w-white',
        'c-white',
        'floor',
        'red',
        'green',
        'blue',
        '_bottom',
      ],
      sections: [
        ['global', 'ahu'],
        ['map'],
        [
          'wohnzimmer',
          'kueche',
          'esszimmer',
          'schlafzimmer',
          'arbeitszimmer',
          'duschbad',
          'wannenbad',
          'terrasse',
          'balkon',
          'flur',
          'abstellraum',
        ],
        ['tech'],
      ],
    },
    strings: {
      abstellraum: 'Abstellraum',
      ahu: 'Lüftung',
      'ahu-control': 'Lüftungssteuerung',
      'ahu-in': 'Lufteinlass',
      'ahu-out': 'Luftauslass',
      air: 'Luft',
      all: 'alle',
      arbeitszimmer: 'Arbeitszimmer',
      aussen: 'außen',
      back: 'hinten',
      balkon: 'Balkon',
      blue: 'blau',
      brightness: 'Helligkeit',
      'c-white': 'kaltweiß',
      'ceiling-lamp': 'Deckenlampe',
      clock: 'Uhr',
      close: 'zu',
      co: 'CO',
      co2: 'CO₂',
      connected: 'verbunden',
      connections: 'Verbindungen',
      decrease: '-',
      'deg-c': '°C',
      delayed: 'verzögert',
      disconnected: 'getrennt',
      door: 'Tür',
      doors: 'Türen und Fenster',
      duschbad: 'Duschbad',
      eco2: 'Eq. CO₂',
      'entry-door': 'Wohnungstür',
      esszimmer: 'Esszimmer',
      fan: 'Ventilator',
      'flood-lamp': 'Flutlicht',
      floor: 'Boden',
      'flow-rate': 'Durchfluss',
      flur: 'Flur',
      fridge: 'Kühlschrank',
      front: 'vorne',
      global: 'global',
      green: 'grün',
      group: 'Gruppe',
      hpa: 'hPa',
      humidity: 'Luftfeuchtigkeit',
      inactive: 'inaktiv',
      increase: '+',
      innen: 'innen',
      kueche: 'Küche',
      lamp: 'Lampe',
      lamps: 'Lampen',
      led: 'LED',
      left: 'links',
      lux: 'lux',
      'm3/h': 'm³/h',
      map: 'Karte',
      mean: '⌀',
      median: 'x͂',
      'micrograms/m3': 'µg/m³',
      'mirror-lamp': 'Spiegellampe',
      'mm/h': 'mm/h',
      movement: 'Bewegung',
      nightstand: 'Nachttisch',
      no: 'nein',
      off: 'aus',
      on: 'ein',
      open: 'offen',
      other: 'Sonstiges',
      percent: '%',
      'percent-rh': '%RH',
      pm025: 'PM (2,5 µm)',
      pm10: 'PM (10 µm)',
      power: 'Power',
      ppb: 'ppb',
      ppm: 'ppm',
      precipitation: 'Niederschlag',
      pressure: 'Luftdruck',
      red: 'rot',
      rgb: 'RGB',
      right: 'rechts',
      schlafzimmer: 'Schlafzimmer',
      security: 'Sicherheit',
      'security-system': 'Alarmanlage',
      'standing-lamp': 'Stehlampe',
      'stone-lamp': 'Steinlampe',
      target: 'Soll',
      tech: 'Tech',
      temperature: 'Temperatur',
      terrasse: 'Terrasse',
      timer: 'Timer',
      trendDown: '▼',
      trendUp: '▲',
      triggered: 'ausgelöst',
      tvoc: '𝓉VOCs',
      unknown: '?',
      up: 'oben',
      'w-white': 'warmweiß',
      wannenbad: 'Wannenbad',
      window: 'Fenster',
      'window-door': 'Fenstertür',
      wohnzimmer: 'Wohnzimmer',
      yes: 'ja',
    },
  },
};
